# API server production Dockerfile
FROM node:21-alpine3.18

WORKDIR /app

COPY package.json .

RUN NODE_OPTIONS="--max-old-space-size=4096" npm install

COPY . .

RUN npm run build

EXPOSE 3001

CMD ["npm", "run","start:prod"]