version: "3.8"
services:
  frontclient:
    container_name: frontclient
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    image: dockerjihun/tzc-front:latest
    ports:
      - "80:80"
    depends_on:
      - apiserver
      - dbserver
  apiserver:
    container_name: apiserver
    build:
      context: ./back/server_API
      dockerfile: Dockerfile.prod
    image: dockerjihun/tzc-apiserver:latest
    ports:
      - "3001:3001"
    env_file:
    #   - ./back/server/config/.env.prod
      - ./docker-config/apiserver-config/.env.prod
  dbserver:
    container_name: dbserver
    
    build:
      context: ./back/server_DB
      dockerfile: Dockerfile.prod
    image: dockerjihun/tzc-dbserver:latest
    ports:
      - "3002:3002"
    env_file:
    #   - ./back/server_DB/config/.env.prod
      - ./docker-config/dbserver-config/.env.prod   