FROM node as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html
# 멀티스테이지 build 이미지에서 COPY 된 /app/nginx.conf 파일을 /etc/nginx/conf.d로 복사
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]