export const ENV_PORT_KEY ='PORT'
export const ENV_FRONT_ORIGIN_KEY='FRONT_ORIGIN'
export const ENV_DB_SERVER_ORIGIN_KEY='DB_SERVER_ORIGIN'
export const ENV_KAKAO_REST_API_KEY_KEY='KAKAO_REST_API_KEY'
export const ENV_KAKAO_REDIRECT_URI_KEY='KAKAO_REDIRECT_URI'

